# Generated by Django 5.1.5 on 2025-02-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultrarede', '0002_alter_users_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
