# Generated by Django 5.1.5 on 2025-02-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultrarede', '0003_verifications_users_checked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verifications',
        ),
    ]
