# Generated by Django 5.1.5 on 2025-02-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultrarede', '0007_remove_users_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
