# Generated by Django 5.1.5 on 2025-02-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultrarede', '0009_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures_post'),
        ),
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures_user'),
        ),
    ]
